# PopCo Monitor Configuration
# Window / layout
window_width=640
window_height=480
resizable=true
borderless=false
always_on_top=false
pos_x=959
pos_y=459
opacity=1.00

# Data
refresh_ms=2000

# Theme settingsl
font_path=./fonts/ShareTechMono-Regular.ttf
font_size=14
amber_r=255
amber_g=176
amber_b=0

enable_scanlines=true
enable_vignette=true
enable_glow=true
enable_flicker=true
enable_chromatic_aberration=true
